using Microsoft.VisualStudio.TextTemplating.VSHost;
using System.Runtime.InteropServices;
using System.Text;

namespace VsixSynchronizer
{
    [Guid("62949701-e45c-41fe-8304-eaf34569010d")]
    public sealed class VsixManifestGenerator : BaseCodeGeneratorWithSite
    {
        public const string Name = nameof(VsixManifestGenerator);

        public const string Description =
            "Generates .NET source code for .vsixmanifest files.";

        public override string GetDefaultExtension()
            => ".cs";

        protected override byte[] GenerateCode(string inputFileName,
            string inputFileContent)
        {
            var manifest = VsixManifestParser.FromManifest(inputFileContent);
            var code = GenerateClass(manifest);
            return Encoding.UTF8.GetBytes(code);
        }

        /// <summary>
        /// Generates the code for the <c>VsixAttributes</c> class using the information
        /// found in the specified <paramref name="manifest" />.
        /// </summary>
        /// <param name="manifest">
        /// (Required.) Reference to an instance of
        /// <see cref="T:VsixSynchronizer.VsixManifest" /> that provides the information to
        /// be written to the generated code.
        /// </param>
        /// <returns>
        /// String containing the text to be written to the output file.
        /// <para />
        /// If the <paramref name="manifest" /> parameter is passed a
        /// <see langword="null" /> reference, then this method returns the empty string.
        /// </returns>
        private string GenerateClass(VsixManifest manifest)
        {
            if (manifest == null)
                return string.Empty;

            var sb = new StringBuilder();
            sb.AppendLine(
                "// ------------------------------------------------------------------------------"
            );
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine(
                $"//     This file was generated by {Vsix.Name}.  Changes made to the code in this "
            );
            sb.AppendLine(
                "//      file will be lost the next time that the project is built."
            );
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine(
                "// ------------------------------------------------------------------------------"
            );

            sb.AppendLine($"namespace {FileNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    internal sealed partial class VsixAttributes");
            sb.AppendLine("    {");
            sb.AppendLine(
                $"        public const string Id = \"{EscapeString(manifest.ID)}\";"
            );
            sb.AppendLine(
                $"        public const string Name = \"{EscapeString(manifest.Name)}\";"
            );
            sb.AppendLine(
                $"        public const string Description = @\"{EscapeVerbatimString(manifest.Description)}\";"
            );
            sb.AppendLine(
                $"        public const string Language = \"{EscapeString(manifest.Language)}\";"
            );
            sb.AppendLine(
                $"        public const string Version = \"{EscapeString(manifest.Version)}\";"
            );
            sb.AppendLine(
                $"        public const string Author = \"{EscapeString(manifest.Author)}\";"
            );
            sb.AppendLine(
                $"        public const string Tags = \"{EscapeString(manifest.Tags)}\";"
            );
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string EscapeString(string value)
            => value?.Replace("\\", "\\\\")
                    .Replace("\"", "\\\"");

        private static string EscapeVerbatimString(string value)
            => value?.Replace("\"", "\"\"");
    }
}