// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixSynchronizer
{
    static class Vsix
    {
        public const string Id = "d7834c28-6a0f-4b5a-b3e0-735dc78cd439";
        public const string Name = "VSIX Synchronizer";
        public const string Description = @"Provides the ability to generate code-behind files for .vsixmanfiest and .vsct files in managed code to make the information easy to consume from the rest of the extension.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "vsix, vssdk";
    }
}
