// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixSynchronizer
{
    internal sealed partial class Vsix
    {
        public const string Id = "751759cc-53b5-45f6-8d75-43392a1dd89c";
        public const string Name = "VSIX Synchronizer";
        public const string Description = @"Provides the ability to generate code-behind files for .vsixmanfiest and .vsct files in managed code to make the information easy to consume from the rest of the extension.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "vsix, vssdk";
    }
}
